### ISSUE TITLE
Symbols, colors and other settings do not work. 

### ISSUE THREAD

**Issue by kjellskogsrud** [randomBrainstormer/MMM-GoogleCalendar#1]
Hi.
Love the module. Solves the family calendar for me without having to make ical's public :)
But when combining multiple calendars in one module I need the colors to work, and right now it doesn't.

Symbols also don't work, and it just sticks with the default.

I tried looking into it, but js is not my language. :P

**Comment by randomBrainstormer** [comment]
Hi @kjellskogsrud! 

Just pushed a few updates which should fix the symbols and colors properties, try updating. Let me know if it works!

**Comment by kjellskogsrud** [comment]
Yupp, seems to work now :) Thanks for that :)

**Comment by randomBrainstormer** [comment]
no problem 👍

**Comment by mirrormonark** [comment]
> Hi. Love the module. Solves the family calendar for me without having to make ical's public :) But when combining multiple calendars in one module I need the colors to work, and right now it doesn't.
> 
> Symbols also don't work, and it just sticks with the default.
> 
> I tried looking into it, but js is not my language. :P

how did you enter multiple calendars? can I have a sample configuration with holiday calendars of nations please
