### ISSUE TITLE
Tv and unlimited input

### ISSUE THREAD

**Issue by Ostedtinkerer** [randomBrainstormer/MMM-GoogleCalendar#11]
Hi

I get an error for this: TypeError: Cannot destructure property 'client_secret'..
I cant seem to find the section for "tv and unlimited input" at the Google Cloud.

All help appriciated. Thanks

**Comment by randomBrainstormer** [comment]
Hi @Ostedtinkerer! 

Try to follow these steps to create the credential:
1. Launch [Google Cloud console](https://console.cloud.google.com/apis/dashboard) and make sure your project is selected in the top bar (next to where it says "Google Cloud Services").
2. In the left side menu under the `Other Products` section you should have the`API and services` option, click here.
3. Once you're in the `API and services` page, look for `credentials` in the left side menu. 
4. To create the credential, click on the `+Create credential` option in the top menu and select `OAuth client ID`. This will navigate to a new page where you can select the TV and unlimited input type. 

You'll need to redo the `node authorize.js` step again with the new credentials.

Let me know how it goes!

**Comment by kid-lat** [comment]
Hi @randomBrainstormer! I am having the same problem.

When creating the OAuth client ID, I chose the only similar-sounding application type option called `TVs and Limited Input devices`. I follow the rest of the directions, but when copying the URL that running `node authorize.js` provides, I get `Error 400: invalid request` and it specifically calls out: `redirect_uri: urn:ietf:wg:oauth:2.0:oob` as not complying with Google policies.

I can't seem to edit the redirect URI myself when choosing `TVs and Limited Input devices` as the application type, and I also get the `Cannot destructure property 'client_secret'` error when choosing another application type.

Using different browsers/machines, as well as incognito mode, does not seem to help.

Thanks in advance!

**Comment by randomBrainstormer** [comment]
manu people seem to have an issue when authorizing `TVs and Limited Input device`, I'm pushing a new version of the module that implements a different `Web Application` as the OAuth credential type, and should make things easier.

**Comment by randomBrainstormer** [comment]
The module was updated and OAuth types changed to `Desktop app`, feel free to open a new issue if you find any problems. Closing this for now.
