### ISSUE TITLE
Error 400:invalid_request

### ISSUE THREAD

**Issue by Wdave40** [randomBrainstormer/MMM-GoogleCalendar#13]
Hey, I am trying to renew my token as usual and this is the response I get after I get the url from node authorize.js 
It says,
You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.

anyone else getting this?

**Comment by randomBrainstormer** [comment]
Hi @Wdave40 I've updated the module so it can use a `Web application` credential, try updating the module and changing the credential to `Web application`. Note: in this new version running `node authorise.js` is no longer needed. 

Let me know how it goes!

**Comment by randomBrainstormer** [comment]
Closing idle issue

**Comment by mirrormonark** [comment]
hi not working
