### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by b-reich** [randomBrainstormer/MMM-GoogleCalendar#16]
Hey, can you please provide a package.json? This would be helpfull mmpm.

**Comment by randomBrainstormer** [comment]
Hi @b-reich, no problem! I'll add this tomorrow. Do you know if the package.json needs to have any specific key included to work with mmpm? Or just the usual basic package will do it? I'm not very familiar with mmpm, didn't know it existed until now!

**Comment by b-reich** [comment]
@randomBrainstormer just a regular package.json will do the job.

**Comment by randomBrainstormer** [comment]
Got it, added in b73029c 💪💪
