### ISSUE TITLE
Error in the MMM-GoogleCalendar module. 

### ISSUE THREAD

**Issue by AnonymousWebDev** [randomBrainstormer/MMM-GoogleCalendar#18]
I get this error everytime. When checking the logs I found a link which brings me to a page that says "error 404, invalid api".
Where do I put in my API? I never put in in nor can I find it in the docs

**Comment by randomBrainstormer** [comment]
Hi @AnonymousWebDev , if you mean your credentials file, you should put it in your MMM-GoogleCalendar directory (MagicMirror/modules/MMM-GoogleCalendar/), also make sure to rename it `credentials.json`

**Comment by randomBrainstormer** [comment]
Closing this issue for now as is idle
