### ISSUE TITLE
Authorize.js just hangs

### ISSUE THREAD

**Issue by pierreode** [randomBrainstormer/MMM-GoogleCalendar#21]
Following the guide for installation, I get the `credentials.json` file and have it in the correct directory. This is confirmed by removing it and receiving and issue when I run `node authorize.json` and getting an error.

My issue is that when I have my `Desktop app` credentials file in the correct location, and the Calendar api enabled on my account, when I run `node authorize.json` via my terminal, nothing happens. It just sits there for hours. I don't get any sort of feedback.

I have installed the latest version of MM and the module. And sort of direction would be great to troubleshoot where I might be going wrong.

**Comment by pierreode** [comment]
Just an update, when running the mirror without authorization, the terminal shows the following error:
```
[LOG]   undefined: Error loading token: [Error: ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/MMM-GoogleCalendar/token.json'
} Make sure you have authorized the app.
```

Where does the `token.json` file come from?

**Comment by randomBrainstormer** [comment]
Hi @pierreode, the module now should open a browser directly in the raspberry pi, maybe you are connecting through SSH hence can't see the browser opening. Try using VNC or connecting the keyboard directly to the PI, and let me know if that's the case, I do think the documentation needs a bit update to clear this part!

**Comment by pierreode** [comment]
Ah!! Yea I am connecting via SSH, that will be the issue. Using a pi I already have setup in another part of the house! I will look into the VNC route!

**Comment by randomBrainstormer** [comment]
Thanks! In the meantime I'll add this bit to the documentation

**Comment by pierreode** [comment]
[Install VNC on Rapberry Pi via SSH](https://www.pitunnel.com/doc/access-vnc-remote-desktop-raspberry-pi-over-internet) was  a great help. Thanks @randomBrainstormer for the guidance!

**Comment by jkaberg** [comment]
@randomBrainstormer I do think this should be more clear (browser part), running MM in an docker container this is obviously not trivial nor self explanatory. Looking into this right now

**Comment by jkaberg** [comment]
@randomBrainstormer very understandable. My usecase involves using server-only (in an docker) to host MM on my NUC. In turn I (chrome)cast MM to an screen. 

This might very well be the "unconventional" way, and for now [I found a way around it](https://github.com/jkaberg/hass-config/blob/master/pyscript/scripts/calendar.py#L9-L40) 😄 (I now use the normal calendar module)
