### ISSUE TITLE
calendar does not display data

### ISSUE THREAD

**Issue by Gandohr** [randomBrainstormer/MMM-GoogleCalendar#40]
Updated yesterday.
log shows no errors and does show: MMM-GoogleCalendar: 10 events loaded for my@email.com
but on screen it gives "no upcoming events"

**Comment by kellypaya1** [comment]
It's the same for me. It seems the node-helper may not be functioning properly... I'm not seeing a log output that indicates the events are being broadcast

**Comment by Gandohr** [comment]
I removed token.json and a new node authorise.js
this works shows events and creates a new token.
but still the calendar shows nothing while the log says it loaded 10 events.

**Comment by pedrompor** [comment]
Yes. Log says it loaded 10 events but nothing showing up in the calendar

**Comment by pedrompor** [comment]
By changing 'timeMax: new Date().toISOString(),' to 'timeMin: new Date().toISOString(),' in node_helper.js fixed it

**Comment by kellypaya1** [comment]
> Changing 'timeMax: new Date().toISOString(),' to 'timeMin: new Date().toISOString(),' in node_helper.js fixed it

Just applied this edit, can confirm fix. Thank you for sharing! 🥳

**Comment by Gandohr** [comment]
Yup Worked for me aswell
thanks

**Comment by randomBrainstormer** [comment]
Hello, bug has been fixed and should be working in the latest update.  

Thank you all for taking the time to discuss about this bug and find a solution, your contribution helps us improve the quality and stability of this module.

Closing this ticket for now, please post if you have any further issues.
