### ISSUE TITLE
Previous events not showing

### ISSUE THREAD

**Issue by Entropy159** [randomBrainstormer/MMM-GoogleCalendar#48]
I am using this module with the CalendarExt3 module. I have an issue where previous events are not showing, regardless of my config options. Here is my config: 
broadcastPastEvents: true,
broadcastEvents: true,
maximumEntries: 200,
maximumNumberOfDays: 35,
pastDaysCount: 7
Any ideas?

**Comment by PeterFleur** [comment]
I have exactly the same with Calendar3Ext but also with MMM-MonthlyCalendar. Other icals file will show the past events. Only Google doesn't with my Family calendar

**Comment by Entropy159** [comment]
The issue persists even with just the Google calendar module using the default list display.

**Comment by randomBrainstormer** [comment]
Hi! I wanted to let you know that I've released a new version of the plugin that should resolve the issue with past events not showing up.

I would appreciate it if you could check if it's working correctly in the latest version. If you still encounter any issues, please let me know so I can look into it further.

Thank you for your help and for using the plugin!

**Comment by Entropy159** [comment]
Thank you so much! It works great now.
