### ISSUE TITLE
Access blocked: XXX has not completed the Google verification process - Access_denied

### ISSUE THREAD

**Issue by sbonaime** [randomBrainstormer/MMM-GoogleCalendar#49]
Hi,
After running  ```node authorize.js``` in the MMM-GoogleCalendar module directory, a chromium browser appears. I then login using my personal google accounts credentials but I get an Error 403

Any idea ? 

Thanks
<img width="530" alt="Capture d’écran 2023-10-26 à 22 00 25" src="https://github.com/randomBrainstormer/MMM-GoogleCalendar/assets/750709/f63fac18-21a8-4c15-ad1e-7b3e759b7a99">

**Comment by sbonaime** [comment]
I had to ad my email to the "Test users" list in the "OAuth consent screen"

**Comment by randomBrainstormer** [comment]
I'm glad to hear that you were able to resolve the issue, and thank you for sharing the solution. I'll add this case to the troubleshooting guide to help others who might encounter the same problem.
