### ISSUE TITLE
authentication is getting stuck

### ISSUE THREAD

**Issue by 366Cobra** [randomBrainstormer/MMM-GoogleCalendar#50]
I have pasted the credentials.json into the folder and enabled the API.
when i run 'node authorize.js', it gets stuck.  no output, no timeout or anything.
it is supposed to give me a URL to get a code, right?
any idea?

**Comment by battlehax** [comment]
Any workaround for this? There is no pi in my setup and I'm running mm as a server in a tiny container.

**Comment by nobbie25** [comment]
What OS are you running on your container? Does it have a UI?  You should be able to access the UI of your container via vnc and open a web browser.  I’ve got a bunch of containers running and I install a desktop for this reason.

**Comment by battlehax** [comment]
I'm running minimal Debian with no X as a magicmirror server that's accessed by several devices on my network.

**Comment by 366Cobra** [comment]
> are you doing this from the UI or from command line via SSH. When you run node authorize you need to be on the UI of the rpi because it opens up the browser to make you click allow
thanks for the reply. 
there is the issue.  i use ssh to configure it, as it is fitted above our range hood in the kitchen.
is there a way to get it done via ssh?

**Comment by 366Cobra** [comment]
> are you doing this from the UI or from command line via SSH. When you run node authorize you need to be on the UI of
> the rpi because it opens up the browser to make you click allow

thanks for the reply. 
there is the issue.  i use ssh to configure it, as it is fitted above our range hood in the kitchen.
is there a way to get it done via ssh?

**Comment by nobbie25** [comment]
I configure mine via SSH and CLI too as its mounted on a wall with no access to a mouse and keyboard but I knew that there would be the need to have access to the UI to fix and configure issues so I installed an X and a vnc client. I would highly recommend doing both if you haven't.. The only other workaround would be to either rewrite the authorize to follow OAuth a command line input verification or to try and manually authorize using this  https://developers.google.com/identity/gsi/web/guides/devices

**Comment by randomBrainstormer** [comment]
Hi, unfortunately this plugin doesn't support SSH authentication any longer. The latest updated module forces a browser to open in the Pi itself, hence you're unable to see it when connecting through SSH. 
As suggested by @nobbie25 , try using VNC or try connecting the keyboard/mouse directly to the pi
