### ISSUE TITLE
Periodic Invalid Grant

### ISSUE THREAD

**Issue by alexio215** [randomBrainstormer/MMM-GoogleCalendar#59]
Hello, I keep getting invalid grant every few days or weeks or so. I do not know exactly when it stops. However, it is periodic.

I delete my token file. And run authorize from scratch. It tends to work for a few days, and then stops. Is there a common issue that I am not aware of? Has anyone taken any steps to diagnose this?

Thank you kindly in advance.

**Comment by randomBrainstormer** [comment]
Hi @alexio215 , this is a common issue, it typically arises when your app remains in "test" mode, leading to tokens expiring approximately every week or so. To resolve this, you need to publish your app on Google Cloud Platform: 
1. Navigate to your Google Cloud Project. 
3. Go to the "OAuth consent screen" tab. 
4. 3. Locate the "Publishing Status" section. 
5. 4. Here, you should see an option to "Publish App." Click this button. 
6. 5. Review and confirm the necessary permissions as prompted. 
7. By publishing your app, you extend the token's lifespan, eliminating the need for frequent reauthorizations.

**Comment by alexio215** [comment]
@randomBrainstormer Thank you very much. I just had a quick question regarding this. Does it become an issue of it becoming available to the public? Or does the data and module stay private? Thank you, and apologies if any of the questions come as naive.

**Comment by Kayakbabe** [comment]
Changing the credentials to take it out of testing mode worked great for me. Thanks randomBrainstormer for explaining it so well.

**Comment by randomBrainstormer** [comment]
Closing this issue for now, but if you require any further assistance, feel free to let me know, @alexio215
