### ISSUE TITLE
Compatibility between last GoogleCalendar update v1.1.2 and CalendarExt3

### ISSUE THREAD

**Issue by Printasaurus** [randomBrainstormer/MMM-GoogleCalendar#62]
It seems like there might be compatibility issues between the latest GoogleCalendar update and the CalendarExt3 module.
Since neither the config.js nor the CalendarExt3 module has changed, the problem likely is caused by the GoogleCalendar update or better a change that has been done.
I am able to see some events after running authorize.js in the terminal, it indicates that events are being loaded, so there might be something in the config.js that needs adjustment to ensure proper functionality?
Is some change of the former config necessary after the last update?

**Comment by KoboseHome** [comment]
@Printasaurus How are you showing the events from the MMM-GoogleCalendar using CalendarExt3?  I am trying to show a full week of events using CalendarExt3, and am struggling as I am not super experienced in MM or linux coding.
