### ISSUE TITLE
The API returned an error: Error: invalid_grant

### ISSUE THREAD

**Issue by daha1989** [randomBrainstormer/MMM-GoogleCalendar#7]
After restarting my Pi the calendar was giving me an error message.
I tried troubleshooting with node authorize.js and received the following:
The API returned an error: Error: invalid_grant

Any advice for that?

**Comment by randomBrainstormer** [comment]
Hi @daha1989, `invalid_grant` usually indicates that the access token is incorrect or invalid. I would try this steps:

1. Make sure the email used during `node authorize.js` is the same OR has access to the credentials in Google Cloud.
2. Completely delete the current token by navigating to the `MMM-GoogleCalendar` directory and deleting `token.json`, if you connect to the raspberry through SSH try running `rm -rf token.json` to delete the token, once deleted run `node authorize.js` again.
3.  If step 2 doesn't work try creating a new credential and repeating the authorize process. 

Let me know how it goes!

**Comment by daha1989** [comment]
It worked. Thanks a lot!
