### ISSUE TITLE
Can't find calendar id?

### ISSUE THREAD

**Issue by Djeloan** [randomBrainstormer/MMM-GoogleCalendar#8]
Hello, i did everything from the instructions, but when i run node authorize.js and complete verification it just lists 10 upcoming events, but i can't find my calendar ID anywhere.

![Capture](https://user-images.githubusercontent.com/5245733/151430121-790dfc16-6c6d-45be-a5b5-6bc4dfa05af5.PNG)

**Comment by randomBrainstormer** [comment]
Hi @Djeloan, if the calendar ID isn't shown you can find your calendar ID straight from your google calendar settings, probably [this guide](https://feed.mikle.com/support/find-your-google-calendar-id/) can belp.  Basically,  just visit [https://calendar.google.com](https://calendar.google.com/) and look for the settings (should be on the upper right section, an icon similar to a gear).  Once you're in the settings page, look on the left for your `calendar settings` and click on the calendar you want to display in `MMM-GoogleCalendar`, you're calendar ID will be somewhere in the `integrate your calendar` section. 
 
Let me know how it goes!

**Comment by randomBrainstormer** [comment]
@Djeloan were you able to get the module running?

**Comment by Djeloan** [comment]
@randomBrainstormer 
Sorry for not responding sooner, i don't have a lot of time to fiddle with it currently, but i will give it a try soon, and will let you know.
Thank you for help anyways!

**Comment by randomBrainstormer** [comment]
Closing this issue for now, feel free to reopen if you got any questions!
