### ISSUE TITLE
Google calendar was running fine on magic mirror but now i have an issue

### ISSUE THREAD

**Issue by getchethanbr** [randomBrainstormer/MMM-GoogleCalendar#9]
Hi,
I am getting an issue called 'Error in the MMM-GoogleCalendar module. check logs for more details'.
What might be the error and how can I resolve this.
Thanks in advance.

**Comment by randomBrainstormer** [comment]
hi @getchethanbr, usually you just have to authenticate again, have you tried deleting the old token and running `node authorize.js` again?

**Comment by randomBrainstormer** [comment]
Also, you might want to look for the logs for more details, it might show a more specific error

**Comment by letsandeepio** [comment]
hi @randomBrainstormer, I am frequently running into invalid_grant issue which usually goes away with regenerating token ? Is there a way to fix this problem permanently?

**Comment by randomBrainstormer** [comment]
@getchethanbr were you able to get the module running?

**Comment by getchethanbr** [comment]
Hey @randomBrainstormer, yes issue is resolved after authenticating again like you said. Thanks for the help.

**Comment by randomBrainstormer** [comment]
👍 👍
